# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/tianchi_dsds/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/tianchi_dsds/proprietary/bin/illumination_service:system/bin/illumination_service \
    vendor/sony/tianchi_dsds/proprietary/bin/sct_service:system/bin/sct_service \
    vendor/sony/tianchi_dsds/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/sony/tianchi_dsds/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/adsp.b00:system/etc/firmware/adsp.b00 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/adsp.b01:system/etc/firmware/adsp.b01 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/adsp.b05:system/etc/firmware/adsp.b05 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/adsp.b09:system/etc/firmware/adsp.b09 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/adsp.b10:system/etc/firmware/adsp.b10 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/adsp.b11:system/etc/firmware/adsp.b11 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/adsp.mdt:system/etc/firmware/adsp.mdt \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/mba.b00:system/etc/firmware/mba.b00 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/mba.mdt:system/etc/firmware/mba.mdt \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b04:system/etc/firmware/modem.b04 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b05:system/etc/firmware/modem.b05 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b10:system/etc/firmware/modem.b10 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b11:system/etc/firmware/modem.b11 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b13:system/etc/firmware/modem.b13 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b15:system/etc/firmware/modem.b15 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b16:system/etc/firmware/modem.b16 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b17:system/etc/firmware/modem.b17 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b18:system/etc/firmware/modem.b18 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b19:system/etc/firmware/modem.b19 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b20:system/etc/firmware/modem.b20 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b21:system/etc/firmware/modem.b21 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b22:system/etc/firmware/modem.b22 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b25:system/etc/firmware/modem.b25 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b26:system/etc/firmware/modem.b26 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.b27:system/etc/firmware/modem.b27 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/tzhdcp.b00:system/etc/firmware/tzhdcp.b00 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/tzhdcp.b01:system/etc/firmware/tzhdcp.b01 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/tzhdcp.b02:system/etc/firmware/tzhdcp.b02 \
    vendor/sony/tianchi_dsds/proprietary/etc/firmware/tzhdcp.mdt:system/etc/firmware/tzhdcp.mdt \
    vendor/sony/tianchi_dsds/proprietary/lib/libpin-cache.so:system/lib/libpin-cache.so \
    vendor/sony/tianchi_dsds/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/sony/tianchi_dsds/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/sony/tianchi_dsds/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/sony/tianchi_dsds/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/sony/tianchi_dsds/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/sony/tianchi_dsds/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/sony/tianchi_dsds/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/sony/tianchi_dsds/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so
