# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/ivy/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/ivy/proprietary/etc/acdbdata/Handset_cal.acdb:system/etc/acdbdata/Handset_cal.acdb \
    vendor/sony/ivy/proprietary/etc/acdbdata/Speaker_cal.acdb:system/etc/acdbdata/Speaker_cal.acdb \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xb0.img:system/etc/firmware/touch_module_id_0xb0.img \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xb1.img:system/etc/firmware/touch_module_id_0xb1.img \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xb2.img:system/etc/firmware/touch_module_id_0xb2.img \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xb3.img:system/etc/firmware/touch_module_id_0xb3.img \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xba.img:system/etc/firmware/touch_module_id_0xba.img \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xbb.img:system/etc/firmware/touch_module_id_0xbb.img \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xbc.img:system/etc/firmware/touch_module_id_0xbc.img \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xca.img:system/etc/firmware/touch_module_id_0xca.img \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xcb.img:system/etc/firmware/touch_module_id_0xcb.img \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xcc.img:system/etc/firmware/touch_module_id_0xcc.img \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xd0.img:system/etc/firmware/touch_module_id_0xd0.img \
    vendor/sony/ivy/proprietary/etc/firmware/touch_module_id_0xd1.img:system/etc/firmware/touch_module_id_0xd1.img \
    vendor/sony/ivy/proprietary/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
    vendor/sony/ivy/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:system/vendor/firmware/fw_bcmdhd_apsta.bin
